### ISSUE TITLE
Freeze when using some functions

### ISSUE THREAD

**Issue by Kermer** [jrimclean/gdnet#3]
So far I find out that using `ping` or `disconnect` will freeze your process.
In case of `ping` it's kind of understandable, but why when using `disconnect`?

I suppose it will be required to use Threads in both options.

Also timeout time seem to be waaaay to high for the games. It usually takes over 10 seconds till the game realise that server/client disconnected (looking at enet.h it looks like timeout takes 5-30sec).

I think adding function for setting timeout time would be nice.

**Comment by Kermer** [comment]
Honestly connection handling and pinging were the only things why I decided to try out GDNet instead of using built-in UDP and they seem to cause problems ^^

**Comment by empyreanx** [comment]
@Kermer I think I know what is happening and it was silly of me to write it this way. I wrote GDNet in about three days last summer, so please forgive me. The ENet function "enet_host_service" pumps the event queues and I'm using a loop inside a thread that calls this function. When GDNet calls "ping" or "disconnect" it tries to lock a mutex associated with the thread. What is happening is that the loop is spinning the lock on the mutex so that others functions like "disconnect" have a hard time acquiring the lock.

I think what I'll do is create and lock-free "command queue", just like I did with messages and events, but I'm going think about it for a couple days because there might be an easier solution that doesn't involve a major renovation.

It should be easy to support timeouts once I've have the threading issue sorted out.

I really appreciate the time you're taking to test out GDNet - you have my thanks :)

**Comment by empyreanx** [comment]
@Kermer I found a solution and it's much simpler than creating a command queue! I should be able to push the solution either today or tomorrow :)

**Comment by empyreanx** [comment]
@Kermer I just pushed a fix for peer commands. Please let me know how this works for you. Also note (and I'll include this in the documentation) that for 'ping' and 'disconnect' to work you must call them after a successful connection event. Well you can call disconnect before a connection is established, but you won't get the notifications. I'll have the ability to set timeouts implemented in the next day or so.

**Comment by empyreanx** [comment]
@Kermer I will also implement more of the ping API for you.

**Comment by empyreanx** [comment]
@Kermer Implemented accessor for round trip time. Note that the default value for RTT is 500 and it gets adjusted with traffic and pings.

I'll try to implement a function for setting timeouts in a day or so, with updated documentation.

**Comment by empyreanx** [comment]
Requested functionality has been implemented.
